name: BlockSwapper
version: 1.3.0
author: WinterBear
main: dev.snowcave.blockswapper.BlockSwapperListener
api-version: 1.13
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.23
permissions:
  blockswapper.use:
    default: true
folia-supported: true